# Generated by Django 3.2.6 on 2021-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
